### ISSUE TITLE
[BUG] apply patch.bat will run incorrectly if you use run as admin

### ISSUE THREAD

**Issue by evileyecc1** [hickorysb/Game-Panel-HUD-SIT-Patcher#1]
It's an old windows issue.If you run a bat by click "run as admin"It will auto cd the C:\Windows\System32 and make work dir in there.This will cause the apply_patch.bat can't move the file in right location.
I think it will better to add a 
`cd /d %~dp0`
in the first line

**Comment by AprilCatStreams** [comment]
No, this actually prevents people from being dumb, you should not be running random things you download from the internet as admin. No approved method of installing SIT, or the mod for that method, will put it in a location that requires admin to run the patcher.
